import React, { useMemo, useState } from "react";
import { ArrowRight, BookOpen, CalendarDays, Clock3, Search } from "lucide-react";
import { Link } from "wouter";
import PublicFooter from "@/components/PublicFooter";
import PublicHeader from "@/components/PublicHeader";
import { useLocale } from "@/contexts/LocaleContext";
import { blogPosts } from "@/lib/blogContent";

export default function Blog() {
  const { locale } = useLocale();
  const isBn = locale === "bn";
  const [category, setCategory] = useState("All");
  const categories = ["All", ...Array.from(new Set(blogPosts.map((post) => post.category)))];
  const posts = useMemo(() => category === "All" ? blogPosts : blogPosts.filter((post) => post.category === category), [category]);
  return <div className="min-h-screen bg-[#f7faff] text-slate-950"><PublicHeader /><main>
    <section className="border-b border-slate-200 bg-white px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.16em] text-blue-700"><BookOpen className="h-3.5 w-3.5" />{isBn ? "invoice-gen.net রিসোর্স" : "invoice-gen.net resources"}</p><h1 className="mt-6 text-4xl font-black tracking-[-0.04em] text-slate-950 sm:text-6xl">{isBn ? "ইনভয়েসিং, cash flow ও ছোট ব্যবসার গাইড" : "Practical ideas for clearer invoicing and healthier cash flow"}</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-600 sm:text-lg">{isBn ? "বাস্তব billing workflow, customer communication, currency এবং payment নিয়ে সহজ, original গাইড পড়ুন।" : "Read original, practical guides about billing workflows, customer communication, currencies, and getting paid."}</p></div></div></section>
    <section className="px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-5 border-b border-slate-200 pb-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-blue-700">{isBn ? "বিষয় অনুযায়ী পড়ুন" : "Browse by topic"}</p><p className="mt-2 text-sm text-slate-500">{isBn ? "আপনার পরের billing question দিয়ে শুরু করুন।" : "Start with the billing question in front of you."}</p></div><div className="flex flex-wrap gap-2" role="group" aria-label={isBn ? "ব্লগ category" : "Blog categories"}>{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-full px-4 py-2 text-xs font-bold transition ${category === item ? "bg-blue-700 text-white shadow-lg shadow-blue-200" : "bg-white text-slate-600 ring-1 ring-slate-200 hover:text-blue-700"}`}>{item === "All" ? (isBn ? "সব" : "All") : item}</button>)}</div></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{posts.map((post, index) => <article key={post.slug} className={`group flex flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl hover:shadow-blue-100/50 ${index === 0 ? "lg:col-span-2" : ""}`}><div className={`relative flex h-40 items-end overflow-hidden bg-gradient-to-br ${index === 0 ? "from-blue-700 via-blue-600 to-cyan-400" : index === 1 ? "from-slate-900 to-blue-800" : "from-cyan-600 to-blue-700"} p-6 text-white`}><div className="absolute -right-8 -top-8 h-32 w-32 rounded-full border-[18px] border-white/10" /><p className="relative text-xs font-bold uppercase tracking-[0.16em] text-blue-100">{post.category}</p></div><div className="flex flex-1 flex-col p-6"><div className="flex items-center gap-4 text-xs font-semibold text-slate-400"><span className="inline-flex items-center gap-1"><CalendarDays className="h-3.5 w-3.5" />{post.published}</span><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5" />{post.readTime}</span></div><h2 className="mt-5 text-xl font-black leading-tight tracking-tight text-slate-950 group-hover:text-blue-700">{post.title[isBn ? "bn" : "en"]}</h2><p className="mt-3 flex-1 text-sm leading-6 text-slate-600">{post.excerpt[isBn ? "bn" : "en"]}</p><Link href={`/blog/${post.slug}`} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-blue-700">{isBn ? "পুরো গাইড পড়ুন" : "Read the guide"}<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></Link></div></article>)}</div></div></section>
  </main><PublicFooter /></div>;
}
