import { Button } from "@/components/ui/button";
import { InvoiceDocument } from "@/components/InvoiceDocument";
import { useLocale } from "@/contexts/LocaleContext";
import { createInvoicePdf } from "@/lib/invoicePdf";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, Download, Mail, Printer } from "lucide-react";
import React, { useState } from "react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";

export default function InvoiceDetail() {
  const { t, locale } = useLocale(); const [, navigate] = useLocation(); const [, params] = useRoute("/invoices/:id"); const id = Number(params?.id); const utils = trpc.useUtils(); const [isExporting, setIsExporting] = useState(false);
  const query = trpc.invoices.detail.useQuery({ id }, { enabled: Number.isFinite(id) && id > 0 }); const changeStatus = trpc.invoices.updateStatus.useMutation({ onSuccess: () => { utils.invoices.detail.invalidate({ id }); utils.invoices.list.invalidate(); toast.success("Invoice status updated"); }, onError: (error) => toast.error(error.message) }); const sendEmail = trpc.invoices.sendEmail.useMutation({ onSuccess: () => { utils.invoices.detail.invalidate({ id }); utils.invoices.list.invalidate(); toast.success(locale === "bn" ? "ইনভয়েস ইমেইলে পাঠানো হয়েছে" : "Invoice email sent"); }, onError: (error) => toast.error(error.message) });
  const generatePdf = async () => { const element = document.getElementById("invoice-print-area"); if (!element) throw new Error("Invoice preview is unavailable"); return createInvoicePdf(element); };
  const exportPdf = async () => { if (!query.data) return; setIsExporting(true); try { const pdf = await generatePdf(); pdf.save(`${query.data.invoice.invoiceNumber}.pdf`); toast.success(locale === "bn" ? "PDF ডাউনলোড হচ্ছে" : "Invoice PDF is downloading"); } catch { toast.error(locale === "bn" ? "PDF তৈরি করা যায়নি" : "Unable to create the PDF"); } finally { setIsExporting(false); } };
  const emailInvoice = async () => { setIsExporting(true); try { const pdf = await generatePdf(); const base64 = pdf.output("datauristring").split(",")[1]; if (!base64) throw new Error("Unable to prepare the invoice PDF"); await sendEmail.mutateAsync({ id, locale: locale === "bn" ? "bn" : "en", pdfBase64: base64 }); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to prepare the invoice email"); } finally { setIsExporting(false); } };
  if (query.isLoading) return <div className="container max-w-7xl py-10 text-sm text-slate-500">Loading invoice…</div>; if (query.isError || !query.data) return <div className="container max-w-7xl py-10"><Button variant="outline" onClick={() => navigate("/invoices")}><ArrowLeft className="mr-2 h-4 w-4"/>{t("backToInvoices")}</Button><p className="mt-5 text-sm text-red-600">The requested invoice could not be found.</p></div>;
  const status = query.data.invoice.status;
  return <div className="container max-w-7xl"><section className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between print:hidden"><div><button onClick={() => navigate("/invoices")} className="mb-3 inline-flex items-center gap-2 text-sm font-semibold text-blue-700 hover:text-blue-900"><ArrowLeft className="h-4 w-4"/>{t("backToInvoices")}</button><h1 className="text-3xl font-bold tracking-tight text-slate-950">{t("invoicePreview")}</h1><p className="mt-2 text-sm text-slate-500">{query.data.invoice.invoiceNumber}</p></div><div className="flex flex-wrap items-center gap-2"><select aria-label="Update payment status" value={status} onChange={(event) => changeStatus.mutate({ id, status: event.target.value as any })} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm font-medium text-slate-700 outline-none focus:border-blue-500"><option value="draft">{t("draft")}</option><option value="sent">{t("sent")}</option><option value="paid">{t("paid")}</option><option value="overdue">{t("overdue")}</option></select><Button variant="outline" onClick={() => window.print()}><Printer className="mr-2 h-4 w-4"/>{t("printPdf")}</Button><Button variant="outline" disabled={isExporting || sendEmail.isPending} onClick={exportPdf}><Download className="mr-2 h-4 w-4"/>{isExporting ? "PDF…" : "PDF"}</Button><Button className="bg-blue-700 hover:bg-blue-800" disabled={isExporting || sendEmail.isPending} onClick={emailInvoice}><Mail className="mr-2 h-4 w-4"/>{sendEmail.isPending ? "Sending…" : t("sendEmail")}</Button></div></section><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_260px]"><InvoiceDocument data={query.data}/><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-5 print:hidden"><h2 className="font-bold text-slate-900">{t("paymentTimeline")}</h2><div className="mt-5 space-y-4">{query.data.history.map((entry) => <div key={entry.id} className="flex gap-3"><div className="mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-blue-50 text-blue-700"><CheckCircle2 className="h-3.5 w-3.5"/></div><div><p className="text-sm font-semibold capitalize text-slate-800">{entry.status === "draft" ? t("draft") : entry.status === "sent" ? t("sent") : entry.status === "paid" ? t("paid") : t("overdue")}</p><p className="mt-1 text-xs text-slate-500">{new Intl.DateTimeFormat(locale === "bn" ? "bn-BD" : "en-BD", { day: "numeric", month: "short", year: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(entry.changedAt))}</p></div></div>)}{!query.data.history.length ? <p className="text-sm text-slate-500">No status changes recorded.</p> : null}</div></aside></div></div>;
}
