import { Button } from "@/components/ui/button";
import { useLocale } from "@/contexts/LocaleContext";
import { trpc } from "@/lib/trpc";
import { Building2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

type ProfileForm = { name: string; nameBn: string; address: string; addressBn: string; email: string; phone: string };
const emptyProfile: ProfileForm = { name: "", nameBn: "", address: "", addressBn: "", email: "", phone: "" };
const asOptional = (value: string) => value.trim() || null;

export default function Settings() {
  const { t, locale } = useLocale(); const { data: profile, isLoading } = trpc.business.get.useQuery(); const [form, setForm] = useState<ProfileForm>(emptyProfile); const save = trpc.business.save.useMutation({ onSuccess: () => toast.success(t("profileSaved")), onError: (error) => toast.error(error.message) });
  useEffect(() => { if (profile) setForm({ name: profile.name, nameBn: profile.nameBn ?? "", address: profile.address ?? "", addressBn: profile.addressBn ?? "", email: profile.email ?? "", phone: profile.phone ?? "" }); }, [profile]);
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!form.name.trim()) return toast.error("Business name is required"); save.mutate({ name: form.name.trim(), nameBn: asOptional(form.nameBn), address: asOptional(form.address), addressBn: asOptional(form.addressBn), email: asOptional(form.email), phone: asOptional(form.phone) }); };
  return <div className="container max-w-3xl"><section><p className="text-sm font-semibold text-blue-700">InvoiceFlow</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">{t("businessInfo")}</h1><p className="mt-2 text-sm text-slate-500">{locale === "bn" ? "এই তথ্য প্রতিটি ইনভয়েসে প্রেরকের তথ্য হিসেবে দেখা যাবে।" : "These details appear as your business information on every invoice."}</p></section><form onSubmit={submit} className="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-6 grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-700"><Building2 className="h-5 w-5"/></div>{isLoading ? <p className="text-sm text-slate-500">Loading…</p> : <div className="grid gap-5 md:grid-cols-2"><ProfileField label={t("businessName")} value={form.name} onChange={(name) => setForm({ ...form, name })} required/><ProfileField label={t("bengaliName")} value={form.nameBn} onChange={(nameBn) => setForm({ ...form, nameBn })}/><ProfileField label={t("email")} value={form.email} type="email" onChange={(email) => setForm({ ...form, email })}/><ProfileField label={t("phone")} value={form.phone} onChange={(phone) => setForm({ ...form, phone })}/><div className="md:col-span-2"><ProfileField label={t("address")} value={form.address} text onChange={(address) => setForm({ ...form, address })}/></div><div className="md:col-span-2"><ProfileField label={t("bengaliAddress")} value={form.addressBn} text onChange={(addressBn) => setForm({ ...form, addressBn })}/></div></div>}<Button type="submit" disabled={save.isPending} className="mt-7 bg-blue-700 hover:bg-blue-800">{save.isPending ? "Saving…" : t("save")}</Button></form></div>;
}

function ProfileField({ label, value, onChange, type = "text", text = false, required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; text?: boolean; required?: boolean }) { return <label className="block text-sm font-medium text-slate-700"><span className="mb-1.5 block">{label}{required ? <span className="text-red-500"> *</span> : null}</span>{text ? <textarea rows={3} value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-blue-500"/> : <input required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="h-10 w-full rounded-lg border border-slate-200 px-3 text-sm outline-none focus:border-blue-500"/>}</label>; }
